anticorruption:
  synaptic:
    function:
      source: "filesystem/synaptic/function"
    shared:
      source: "filesystem/synaptic/shared"
  neural:
    areas:
      target: "filesystem/neural/areas"
    neurons:
      target: "filesystem/neural/neurons"
    effectors:
      package: "xxxxx.yyyyy.zzzzz.autopoietic.autonomous.intelligence.effectors.effector"
      source: "adapters/driven/services/src/main/java"
      target: "adapters/driven/services/target/classes"
      compiler:
        classpath:
          strategy: "manual"
          value: "adapters/driven/services/target/classes:specification/target/classes:adapters/driven/anticorruption/target/classes"
  hippocampal:
    episode:
      target: "filesystem/hippocampal/episode"
      limit: "-1"
    knowledge:
      target: "filesystem/hippocampal/knowledge"
