anticorruption:
  synaptic:
    function:
      source: "filesystem/synaptic/function"
    shared:
      source: "filesystem/synaptic/shared"
  neural:
    areas:
      target: "filesystem/neural/areas"
      limit: "-1"
    neurons:
      target: "filesystem/neural/neurons"
      limit: "-1"
    effectors:
      package: "xxxxx.yyyyy.zzzzz.autopoietic.autonomous.intelligence.effectors.effector"
      source: "adapters/driven/services/src/main/java"
      target: "adapters/driven/services/target/classes"
      compiler:
        classpath: "adapters/driven/services/target/classes:specification/target/classes"
  hippocampal:
    episode:
      target: "filesystem/hippocampal/episode"
      limit: "-1"
  neocortical:
    knowledge:
      target: "filesystem/neocortical/knowledge"
      limit: "1"
